# Generated by Django 5.2.17 on 2026-09-24 07:38

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_nonce",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_nonce",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
