# Generated by Django 5.2.17 on 2026-09-13 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticketing", "0002_event_category_images_visibility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("link_token_digest", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="refund_policy",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_minor",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal_minor",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("confirmed", "confirmed"),
                    ("cancelled", "cancelled"),
                    ("refunded", "refunded"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("valid", "valid"),
                    ("checked_in", "checked_in"),
                    ("cancelled", "cancelled"),
                    ("refunded", "refunded"),
                ],
                default="valid",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.PositiveBigIntegerField()),
                ("description", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_entries",
                        to="ticketing.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="PromotionalCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "percent"), ("fixed", "fixed")], max_length=7
                    ),
                ),
                ("discount_value", models.PositiveBigIntegerField()),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("max_redemptions", models.PositiveIntegerField(blank=True, null=True)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaigns",
                        to="ticketing.event",
                    ),
                ),
                (
                    "ticket_types",
                    models.ManyToManyField(
                        blank=True, related_name="campaigns", to="ticketing.tickettype"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="PromoRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("discount_minor", models.PositiveBigIntegerField()),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemption",
                        to="ticketing.order",
                    ),
                ),
                (
                    "promo_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="ticketing.promocode",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="ticketing.promotionalcampaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-redeemed_at", "-pk"],
            },
        ),
        migrations.AddField(
            model_name="promocode",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="codes",
                to="ticketing.promotionalcampaign",
            ),
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount_minor", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund",
                        to="ticketing.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="promotionalcampaign",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_value__gt", 0)), name="campaign_discount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="promotionalcampaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_type", "fixed"), ("discount_value__lte", 100), _connector="OR"
                ),
                name="campaign_percent_within_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotionalcampaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("starts_at__isnull", True),
                    ("ends_at__isnull", True),
                    ("ends_at__gt", models.F("starts_at")),
                    _connector="OR",
                ),
                name="campaign_dates_valid",
            ),
        ),
    ]
